name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.2
      - name: Create file
        run: touch file3
      - name: List Code
        run: ls
      - name: Upload Code
        uses: actions/upload-artifact@v6.0.0
        with:
          path: **/file3
        
  
    
